# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af85ff5854c9e93cefe78774f79ba0e827922e71e2ac5bdb30018f7d40cd76d1c6a220d4110d766ff8c610ac4c006c600fb2112365810f44afebc7118a5262bc
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://our_ngrok_url
  
test:
  secret_key_base: 0551a8a0661d8b9a4f54cc3186b66b869b065fa8e7369236683d67a5134632dd459603eedfa9da76b9dcbc4049fcd67e217b86979ddd9e80e57e7280d6c4b4b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: af85ff5854c9e93cefe78774f79ba0e827922e71e2ac5bdb30018f7d40cd76d1c6a220d4110d766ff8c610ac4c006c600fb2112365810f44afebc7118a5262bc
